trigger:
- master

jobs:
- job: windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - script: |
      git submodule update --init --recursive
    displayName: 'Init'
  - script: |
      cd 3rd\luamake
      tools\ninja.exe -f ninja\msvc.ninja
      cd ..\..
    displayName: 'Compile luamake'
  - script: |
      3rd\luamake\luamake.exe rebuild
    displayName: 'Compile'
  - script: |
      server\bin\lua-language-server.exe server\publish.lua
    displayName: 'Publish'
  - task: CopyFiles@2
    inputs:
      Contents: '**'
      SourceFolder: 'publish\lua-language-server'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: sumneko.lua-windows

- job: macos
  pool:
    vmImage: 'macos-latest'

  steps:
  - bash: |
      git submodule update --init --recursive
    displayName: 'Init'
  - bash: |
      sudo xcode-select -s /Applications/Xcode_10.2.app
      brew install ninja
    displayName: 'Install'
  - bash: |
      cd 3rd/luamake
      ninja -f ninja/macos.ninja
      cd ../..
    displayName: 'Compile luamake'
  - bash: |
      ./3rd/luamake/luamake rebuild
    displayName: 'Compile'
  - bash: |
      server/bin/lua-language-server server/publish.lua
    displayName: 'Publish'
  - task: CopyFiles@2
    inputs:
      Contents: '**'
      SourceFolder: 'publish/lua-language-server'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: sumneko.lua-macos

- job: linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - bash: |
      git submodule update --init --recursive
    displayName: 'Init'
  - bash: |
      sudo apt-get install -y libreadline-dev ninja-build
    displayName: 'Install'
  - bash: |
      cd 3rd/luamake
      ninja -f ninja/linux.ninja
      cd ../..
    displayName: 'Compile luamake'
  - bash: |
      ./3rd/luamake/luamake rebuild
    displayName: 'Compile'
  - bash: |
      server/bin/lua-language-server server/publish.lua
    displayName: 'Publish'
  - task: CopyFiles@2
    inputs:
      Contents: '**'
      SourceFolder: 'publish/lua-language-server'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: sumneko.lua-linux
