trigger:
- master

jobs:
- job: windows_msvc
  pool:
    name: Hosted VS2017

  steps:
  - script: |
      git submodule update --init --recursive
    displayName: '拉取子模块'
  - script: |
      cd 3rd/luamake
      tools/ninja -f ninja/msvc.ninja
      cd ../..
    displayName: 'PreCompile'
  - script: |
      3rd/luamake/luamake.exe rebuild
    displayName: 'Compile'

- job: macos
  pool:
    name: Hosted macOS

  steps:
  - bash: |
      git submodule update --init --recursive
    displayName: '拉取子模块'
  - bash: |
      sudo xcode-select -s /Applications/Xcode_10.2.app
      brew install ninja
    displayName: '安装ninja'
  - bash: |
      cd 3rd/luamake
      ninja -f ninja/macos.ninja
      cd ../..
    displayName: 'PreCompile'
  - bash: |
      ./3rd/luamake/luamake rebuild
    displayName: 'Compile'

- job: linux
  pool:
    name: Hosted Ubuntu 1604

  steps:
  - bash: |
      git submodule update --init --recursive
    displayName: '拉取子模块'
  - bash: |
      sudo apt-get update
      sudo apt-get install -y libreadline-dev ninja-build
    displayName: '安装ninja'
  - bash: |
      cd 3rd/luamake
      ninja -f ninja/linux.ninja
      cd ../..
    displayName: 'PreCompile'
  - bash: |
      ./3rd/luamake/luamake rebuild
    displayName: 'Compile'
